### ISSUE TITLE
Regarding Dialogflow's V2 API

### ISSUE THREAD

**Issue by zahassanyum** [jschnurr/botkit-middleware-dialogflow#7]
Hi,

Any idea when version 2 of the Dialogflow API would be implemented since it's now generally available and out of beta.

[Migration guide](https://dialogflow.com/docs/reference/v1-v2-migration-guide)

[Official Dialogflow v2 SDK for Node.js](https://github.com/dialogflow/dialogflow-nodejs-client-v2)

— H

**Comment by ehrhart** [comment]
Implemented Dialogflow V2 API for my own needs.

It's available in a [GitHub repository](https://github.com/ehrhart/botkit-middleware-dialogflow-v2) in case someone else needs it.

Two major changes to take into account when porting:
* Dialogflow V2 authentication now requires [Google Cloud Credentials](https://cloud.google.com/docs/authentication/getting-started) instead of a token.
* The raw `nlpResponse` object structure has changed and is completely different since V2.
    * [QueryResult | Dialogflow API](https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.QueryResult)
    * [V1 to V2 mapping | Dialogflow API](https://dialogflow.com/docs/reference/v1-v2-mapping)

**Comment by jschnurr** [comment]
v2.0.2 now supports both Dialogflow API versions v1 and v2.  Complete refactor, updated README and examples using V2.  Thanks @ehrhart - I was able to patch in some of your work.
